server:
  port: 8080

logging:
  level:
    web: info
    sql: info
springdoc:
  use-fqn: true

jwt:
  secret: VlwEyVBsYt9V7zq57TejMnVUyzblYcfPQye08f7MGVA9XkHN

spring:
  profiles:
    active: dev

---

spring:
  config:
    activate:
      on-profile: dev
  main:
    allow-bean-definition-overriding: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: *****************
    username: ****
    password: ****
    initialization-mode: true

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    hibernate:
      ddl-auto: create
  data:
    redis:
      host: localhost
      port: 6379
      password:  ******
    cassandra:
      contact-points: 70.12.246.60
      keyspace-name: tagmanager
      local-datacenter: datacenter1
    hive:
      driver-class-name: org.apache.hive.jdbc.HiveDriver
      jdbc-url: ***************
      username: ****
      password: ****
#  kafka:
#    bootstrap-servers: master01:9092,master02:9092,slave01:9092,slave02:9092,slave03:9092
#    topic:
#      tag-manager: tagmanager
#    producer:
#      bootstrap-servers: master01:9092,master02:9092,slave01:9092,slave02:9092,slave03:9092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#    template:
#      default-topic: tagmanager
  output:
    ansi:
      enabled: always

---

spring:
  config:
    activate:
      on-profile: stage
  main:
    allow-bean-definition-overriding: true

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    jdbc-url: *********************************
    username: ****
    password: ****
    initialization-mode: true

  jpa:
    show-sql: false
    properties:
      hibernate:
        format_sql: true
    database: mysql
    hibernate:
      ddl-auto: update
  data:
    redis:
      host: localhost
      port: 6379
      password:  ***********
    cassandra:
      contact-points: 172.31.58.239:9042
      keyspace-name: tagmanager
      local-datacenter: datacenter1
    hive:
      driver-class-name: org.apache.hive.jdbc.HiveDriver
      jdbc-url: ************
      username: ****
      password: ****
#  kafka:
#    bootstrap-servers: 172.26.3.140:9092
#    topic:
#      tag-manager: tagmanager
#    producer:
#      bootstrap-servers: 172.26.3.140:9092
#      key-serializer: org.apache.kafka.common.serialization.StringSerializer
#      value-serializer: org.apache.kafka.common.serialization.StringSerializer
#    template:
#      default-topic: tagmanager
  output:
    ansi:
      enabled: always
